import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const iranSans = localFont({
  src: [
    {
      path: "./fonts/IRANSansWeb_UltraLight.ttf",
      weight: "200",
    },
    {
      path: "./fonts/IRANSansWeb_Light.ttf",
      weight: "300",
    },
    {
      path: "./fonts/IRANSansWeb.ttf",
      weight: "400",
    },
    {
      path: "./fonts/IRANSansWeb_Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/IRANSansWeb_Bold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/IRANSansWeb_Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-iran-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${iranSans.variable} ${iranSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
